# Site
name: 'Earthling Music Sounds And Tones'
description: 'A newspaper about Earthling music, Earthling sounds, and Earthling tones, written by Earthlings for Earthlings. “Earthling Musics Sounds And Tones” is available in print everywhere in the Andromeda nebula. It is only available on planet Earth using the internet.'
logo: 'assets/images/logo.png'
#favicon: 'assets/images/favicon.ico'
favicon: 'assets/images/icons8-earth-planet-office-96.png'
url: https://earthlingmusic.com/
#url: https://earthlingmusic.github.io/
#baseurl: '/earthlingmusic/'
baseurl: ''
#disqus: 'demowebsite'
#email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://soundcloud.us10.list-manage.com/subscribe/post?u=dc1c5cf438810073dbe0d8e52&amp;id=5916cbe3a3'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    elon:
      name:           Elon Musk
      site:           https://www.tesla.com/elon-musk
      avatar:         assets/images/1024px-Elon_Musk_Royal_Society.jpg
      bio:            "Real human, interested in Earthling sounds, and Earthling tones, but not Earthling music. Space alien music only."
      email:          elonmusk@gmail.com
      twitter:        https://twitter.com/elonmusk
 
    hume:
      name:           Hume Humon
      site:           https://www.humehumon.net
      avatar:         assets/images/hume-humon.jpeg
      bio:            "Hume Humon is an Earthling journalist human, reporting on Earthling music, Earthling sounds, and Earthling tones."
      email:          humehumon@gmail.com
      twitter:        https://twitter.com/humehumon
 
    homero:
      name:           Homero Sapienzales
      site:           https://www.humehumon.net
      avatar:         assets/images/hume-humon.jpeg
      bio:            "Homero Sapienzales es un periodista terrícola humano que informa sobre música terrícola, sonidos terrícolas y tonos terrícolas."
      email:          humehumon@gmail.com
      twitter:        https://twitter.com/humehumon
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: hume
      avatar: /assets/images/hume-humon.jpeg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
